nft: use clone_into instead of to_owned
clippy says:

error: assigning the result of `ToOwned::to_owned()` may be inefficient
   --> src/module/nft/nft.rs:295:9
    |
295 | /         event.verdict = match raw.v {
296 | |             -1 => "continue",
297 | |             -2 => "break",
298 | |             -3 => "jump",
...   |
309 | |         }
310 | |         .to_owned();
    | |___________________^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#assigning_clones
    = note: `-D clippy::assigning-clones` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::assigning_clones)]`
help: use `clone_into()`

Signed-off-by: Adrian Moreno <amorenoz@redhat.com>